# Generated by Django 6.1 on 2026-08-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenings', '0002_screening_confidence_screening_gradcam_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('quality_data', models.JSONField(blank=True, null=True)),
                ('probabilities', models.JSONField(blank=True, null=True)),
                ('retinal_analysis', models.JSONField(blank=True, null=True)),
                ('original_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('gradcam_url', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='screenings.screening')),
            ],
        ),
    ]
