# Generated by Django 6.1 on 2026-08-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='gradcam_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='original_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='prediction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='probabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='quality_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='retinal_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
