# Generated by Django 6.1 on 2026-08-31 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('category', models.CharField(choices=[('PATIENT', 'Patient'), ('SCREENING', 'Screening'), ('AI_ANALYSIS', 'AI Analysis'), ('REFERRAL', 'Referral'), ('CLINICAL_EVALUATION', 'Clinical Evaluation'), ('COLLECTION', 'Collection'), ('USER_MANAGEMENT', 'User Management'), ('AUTH', 'Authentication')], db_index=True, max_length=40)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=40)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('patient_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('patient_name', models.CharField(blank=True, default='', max_length=150)),
                ('details', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
