# Generated by Django 6.1 on 2026-08-31 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REFERRAL_PENDING', 'New Referral Pending'), ('CASE_ASSIGNED', 'New Case Assigned'), ('CLINICAL_REVIEW_COMPLETED', 'Clinical Review Completed'), ('REPORT_READY_FOR_COLLECTION', 'Report Ready for Collection'), ('REPORT_COLLECTED', 'Report Collected'), ('SYSTEM', 'System Notification')], db_index=True, default='SYSTEM', max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('related_entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
